language: cpp

dist: trusty
sudo: required

cache:
    apt: true

matrix:
    include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
      env: COMPILER=g++-6
      
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
      env: COMPILER=g++-5
    
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-4.9
          sources: *sources
      env: COMPILER=g++-4.9    

    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
      env: COMPILER=clang++-3.8
      
    - compiler: clang 
      addons:
        apt:
          packages:
            - clang-3.7
          sources: *sources
      env: COMPILER=clang++-3.7
      
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
          sources: *sources
      env: COMPILER=clang++-3.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-dev
    #- sudo apt-get update -qq
    #- sudo apt-get install -y libopencv-dev
    - chmod +x ./before_install.sh
    - ./before_install.sh
    
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./optics_tests
