language: generic

dist: trusty
sudo: required

cache:
    apt: true

matrix:
    include:
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
          sources: *sources

script:
    - ./build_and_test.sh

before_install:
    - ./before_install.sh
