language: cpp

dist: trusty
sudo: required

cache:
    apt: true

matrix:
    include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.9
            - llvm-toolchain-precise-4
            - llvm-toolchain-precise-5
      env: COMPILER=g++-6
     
     - compiler: gcc
        addons:
          apt:
            packages:
            - g++-7
            sources: *sources
      env: COMPILER=g++-7

      - compiler: gcc
        addons:
          apt:
            packages:
            - g++-7.2
            sources: *sources
      env: COMPILER=g++-7.2

     - compiler: gcc
        addons:
          apt:
            packages:
            - g++-6.4
            sources: *sources
      env: COMPILER=g++-6.4

     - compiler: gcc
        addons:
          apt:
            packages:
            - g++-5.5
            sources: *sources
      env: COMPILER=g++-5.5

    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
      env: COMPILER=g++-5
    
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.9
          sources: *sources
      env: COMPILER=clang++-3.9

    - compiler: clang
      addons:
        apt:
          packages:
            - clang-4
          sources: *sources
      env: COMPILER=clang++-4

    - compiler: clang
      addons:
        apt:
          packages:
            - clang-5
          sources: *sources
      env: COMPILER=clang++-5
      


before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-dev

    - sudo apt-get install cimg-dev

    #- sudo apt-get update -qq
    #- sudo apt-get install -y libopencv-dev

    - chmod +x ./before_install.sh
    - ./before_install.sh
    
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./optics_tests
