language: cpp

dist: trusty
sudo: required

cache:
    apt: true

matrix:
    include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
      env: CXX=g++-6 CC=gcc-6
      
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
      env: CXX=g++-5 CC=gcc-5
    
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-4.9
          sources: *sources
      env: CXX=g++-4.9 CC=gcc-4.9
    
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-4.0
          sources: *sources
      env: CXX=clang++-4.0 CC=clang-4.0
    
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.9
          sources: *sources
      env: CXX=clang++-3.9 CC=clang-3.9
      

    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
      env: CXX=clang++-3.8 CC=clang-3.8
      
    - compiler: clang 
      addons:
        apt:
          packages:
            - clang-3.7
          sources: *sources
      env: CXX=clang++-3.7 CC=clang-3.7
      
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.6
          sources: *sources
      env: CXX=clang++-3.6 CC=clang-3.6

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-dev
    #- sudo apt-get update -qq
    #- sudo apt-get install -y libopencv-dev
    - chmod +x ./before_install.sh
    - ./before_install.sh
    
#script:
  #- mkdir build
  #- cd build
  #- cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  #- ./dkm_tests
  #- ./dkm_bench
